import { createRequire } from 'node:module'; const require = createRequire(process.env.PWPATH + '/'); const { chromium } = require('playwright');
import fs from 'node:fs';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
const ctx = await b.newContext({ viewport: { width: 1100, height: 900 } });
await ctx.route('**/xlsx.full.min.js', r => r.fulfill({ contentType: 'text/javascript', body: fs.readFileSync('/home/claude/tab/node_modules/xlsx/dist/xlsx.full.min.js', 'utf8') }));
await ctx.route('https://fonts.googleapis.com/**', r => r.fulfill({ contentType: 'text/css', body: '' }));
const p = await ctx.newPage(); p.on('pageerror', e => console.log('ERR', e.message));
await p.clock.setFixedTime(new Date('2026-09-30T08:30:00-03:00'));
await p.goto('http://localhost:3000/'); await p.waitForSelector('#f-login');
await p.screenshot({ path: '/tmp/e_login.png' });
await p.fill('#lg-u', 'equipo.manos'); await p.fill('#lg-p', 'mal'); await p.click('#lg-b'); await p.waitForTimeout(1200);
console.log('bad login:', await p.textContent('#lg-m'));
await p.fill('#lg-p', 'Local12345'); await p.click('#lg-b'); await p.waitForSelector('.eq-hoy');
console.log('equipo modo switch present:', await p.$('.modo') !== null, 'admin present:', await p.$('#adm') !== null);
await p.waitForTimeout(1500); await p.screenshot({ path: '/tmp/e_equipo.png', fullPage: true });
await p.click('.salir'); await p.waitForSelector('#f-login');
await p.fill('#lg-u', 'Joaquin'); await p.fill('#lg-p', 'Prueba12345'); await p.click('#lg-b'); await p.waitForSelector('#adm');
console.log('encargado title:', await p.title());
// upload excel
await p.click('#adm summary');
await p.setInputFiles('#f-xlsx', '/home/claude/ventas.xlsx'); await p.waitForTimeout(12000);
console.log(await p.textContent('#m-xlsx'));
await p.fill('.p7n[data-f="2026-10-02"]', 'Prueba nota'); await p.dispatchEvent('.p7n[data-f="2026-10-02"]', 'change');
await p.click('#b-save3'); await p.waitForTimeout(2500);
console.log('save msg:', await p.textContent('#m-save3'));
await p.reload(); await p.waitForSelector('#adm');
console.log('nota persisted:', await p.inputValue('.p7n[data-f="2026-10-02"]'));
await p.screenshot({ path: '/tmp/e_enc.png' });
await b.close();
